#!/bin/sh
# Date: 2024-03-11 21:00 UTC - last change
# get-ip [list|url]
# $1=file+url+list

: ${1:?required - [file myip-url-list | url]}

test "X$(id -nu)" != 'Xroot' || exit

test -d "${HOME}/download" && { cd "${HOME}/download/" || exit;}

test -f "${1}" || URL=${1} XURL=${1}

test -n "${URL}" || URL=$(randstr-lst "${1:-/etc/lst.d/myip.lst}" "99")
test -n "${URL}" || exit

UA=$(randstr-lst "/etc/lst.d/web_useragent.lst" "40")
REFERER=$(randstr-lst "/etc/lst.d/referer_http.lst" "40")

: ${UA:= }
URL=${URL#*://}
HOST=${URL%%/*}
URL=${URL#$HOST}
test -n "${XURL}" || XURL="http://${HOST}:80/${URL#/}"

set --
#set -- "--header 'GET /${URL#/} HTTP/1.1'"  # wget: server returned error: HTTP/1.1 400 Bad Request
set -- "${1:+${1} }--header 'Host: ${HOST}'"
set -- "${1:+${1} }--header 'User-Agent: ${UA-}'"
set -- "${1:+${1} }--header 'Referer: ${REFERER:-${XURL}}'"
#set -- "${1:+${1} }--header 'Connection: close'"
set -- "${1:+${1} }--no-check-certificate -q -O -"
#set -- "${1:+${1} }'http://${HOST}:80/${URL#/}
set -- "${1:+${1} }'${XURL}'"

ulimit -St '1'

{ eval wget ${1} 2>&1; printf '\n';} | while IFS= read -r S; do
  S=$(printf '%s' "${S}" | sed \
   -e 's/\(.*[^0-9]\|^\)\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\)\([^0-9].*\|$\)/\2/' \
   -e '/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$/!d'
  )
  test -n "${S}" && printf '%s\n' "${S}"
done